### ISSUE TITLE
Viewer doesn't work in Firefox

### ISSUE THREAD

**Issue by alastair** [DDMAL/salzinnes-original#1]
Not sure if this is known... Just putting it here so we don't forget

**Comment by dellsystem** [comment]
It's because of the `console.log()`s I used while debugging. They'll be gone once everything is done.

**Comment by ahankinson** [comment]
If it's an easy fix, OK, but if not we should just target Safari for the demo.

-A

**Comment by alastair** [comment]
You should use

```
if (!window.console || !console.firebug) {
  var names = ["log", "debug", "info", "warn", "error", "assert", "dir", "dirxml", "group", "groupEnd", "time", "timeEnd", "count", "trace", "profile", "profileEnd"];
  window.console = {};
  for (var i = 0; i < names.length; ++i) {
      window.console[names[i]] = function() {};
    }
}
```

Having said that, I turned on the firebug console and it still doesn't work. Toolbar + left panel is there. Diva pane and right panel are missing

**Comment by dellsystem** [comment]
I guess it's a css issue then. I'll look into it tomorrow.

**Comment by ahankinson** [comment]
Also, IE 8+

Please don't hate me.

**Comment by dellsystem** [comment]
Yep, making it work with all modern(-ish) browsers is on my to-do list!
