### ISSUE TITLE
Scrolling for left and right panes

### ISSUE THREAD

**Issue by dellsystem** [DDMAL/salzinnes-original#12]
Doesn't work properly.

**Comment by dellsystem** [comment]
9fe4ebecedcddc5d37692ac79dc33482cc9f6d91

**Comment by alastair** [comment]
We ran into this again on the right pane.

A common use-case may be to select text about the incipit top copy somewhere, so the inadvertent drag-scroll may happen more often than we think.
Not an urgent issue for Thursday, but the side panels may need to be rethought.

**Comment by dellsystem** [comment]
Drag-scroll works mostly fine for the left pane, so presumably there is a way to fix it for the right pane too. I'll see if I get a chance to work on this tomorrow.
