### ISSUE TITLE
"Link to page" icon should behave differently

### ISSUE THREAD

**Issue by dellsystem** [DDMAL/salzinnes-original#13]
The current popup box is awkward and out of place

**Comment by alastair** [comment]
We should also consider if we want the search query and state of the expanders stored in the link (low priority)

**Comment by dellsystem** [comment]
Good idea.

**Comment by dellsystem** [comment]
The state of the expanders is a bit difficult and messy to store. I'm going to scrap that for now, we could open a separate feature request for that later if necessary.
