### ISSUE TITLE
CANTUS logo on webpage

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/salzinnes-original#2]
We need to display the cantus logo on the demo

**Comment by dellsystem** [comment]
What logo, and where?

**Comment by alastair** [comment]
http://publish.uwo.ca/~cantus/
Logo should be at the very least on the info page/popup, or on the main page too (along with DDMAL/McGill/Granting Agency? - @ahankinson)

**Comment by ahankinson** [comment]
I don't think we should hide it on the info page. Maybe something like "data provided by the CANTUS project" or something like that. 

In any case, low priority.
