### ISSUE TITLE
Preserve state of dropdown arrows

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/salzinnes-original#20]
We need a way to preserve the state of dropdown arrows.

**Comment by dellsystem** [comment]
What do you mean by this exactly?

**Comment by dellsystem** [comment]
Doesn't work yet ... reopening

**Comment by dellsystem** [comment]
Should work now.

**Comment by dellsystem** [comment]
The status of concordances isn't saved. Is this necessary?
