### ISSUE TITLE
Tune page switching

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/salzinnes-original#24]
The data for pages should be loaded a bit sooner. They currently load when the page is at the top of the viewport.

This is currently a usability issue for larger monitors.

**Comment by dellsystem** [comment]
It's also a bit buggy when scrolling large distances. I'll look into finding another way to determine the "current" page

**Comment by dellsystem** [comment]
Does this work? Can this be closed?

**Comment by ahankinson** [comment]
Yes, seems to work for me now.
