### ISSUE TITLE
fixedGridHeight: true doesn't work

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/salzinnes-original#35]
The pages in grid view look jagged because of their different heights. Setting fixedGridHeight to true, though, breaks grid view.

Low priority. Fix if it's easy.

**Comment by ahankinson** [comment]
We need to get this fixed before we make it public.

**Comment by dellsystem** [comment]
Figured it out - the Python version of divaserve.php is not returning the `min_ratio`, which is needed to calculate the row heights in grid view. `min_ratio` was only added to divaserve.php fairly recently (a few days before this repository was created) so perhaps it was overlooked when porting it to Python (maybe an older version was used as a reference). I just added it to divaserve.py and everything seems to work now.

**Comment by ahankinson** [comment]
Great. We should merge this in ASAP.
