### ISSUE TITLE
Clear search button

### ISSUE THREAD

**Issue by alastair** [DDMAL/salzinnes-original#4]

**Comment by dellsystem** [comment]
Would an x somewhere on the right side of the input field work?

EDIT: Just noticed that you assigned this to yourself. Are you working on it already?

**Comment by alastair** [comment]
I was thinking about an X, or just some text under - "clear search". I haven't started working on it yet.  Assign it to you if you've made a start.

**Comment by dellsystem** [comment]
I haven't yet but I will now

**Comment by ahankinson** [comment]
An x in the box would be the most consistent with search boxes, like the rounded-x to clear the search in Safari.

You might try this: http://www.brandspankingnew.net/archive/2005/08/adding_an_os_x.html

Or something else.

**Comment by dellsystem** [comment]
I've already seen that, it doesn't include the x though
