### ISSUE TITLE
Search illumination field

### ISSUE THREAD

**Issue by alastair** [DDMAL/salzinnes-original#40]

**Comment by dellsystem** [comment]
What does this mean?

**Comment by alastair** [comment]
We now show the name of the illumination on the pages. We should be able to
search by this name

On Fri, Nov 18, 2011 at 5:32 PM, Wendy Liu <
reply@reply.github.com

**Comment by dellsystem** [comment]
Is there anything I need to do to get this working?

**Comment by alastair** [comment]
We need to index the field in solr and make the server search that field. For the UI we might want to show the illumination name on the search results (in bold) to show that's where the match is from
