### ISSUE TITLE
Length of returned results

### ISSUE THREAD

**Issue by dellsystem** [DDMAL/salzinnes-original#47]
For example, for the third jesus result, the text is a bit lengthy and forces the search results box to be taller than I'd like. Would truncating the text (either client-side or server-side) be an option? If not, do we know the maximum possible length that might be returned?

Priority: All of them

**Comment by alastair** [comment]
The length of the snippet is calculated by solr. I'm not sure if there's a
guarantee that there will be words at the beginning or end that are not
highlighted. I'll look up the highlighting docs.

On Thu, Nov 24, 2011 at 7:27 PM, Wendy Liu <
reply@reply.github.com

**Comment by alastair** [comment]
@dellsystem we can change the length of the returned fragment by changing the hl.fragsize parameter - http://wiki.apache.org/solr/HighlightingParameters#hl.fragsize
I saw though that the specific example you gave has enough space now. Did you make the results box bigger, and if so, do you want to make it smaller again?
