### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by alastair** [DDMAL/salzinnes-original#7]
Check that updated colours are committed to the repo

**Comment by dellsystem** [comment]
What does this mean?

**Comment by alastair** [comment]
Sorry. Andrew said that the colours on my version looked different to the changes that you made (that were live on petrucci). So either the changes weren't committed, or Andrew needs new eyes

**Comment by dellsystem** [comment]
Oh, haha I see. Andrew's eyes are fine - I initially changed the background colour to the shade of light blue that Andrew specified but I'm not a big fan of how it looks (it just feels too bright to me) so I changed it back to what we had before (dark grey, similar to OS X Preview). Is this okay or should I make it light blue again?

**Comment by alastair** [comment]
@ahankinson can you weigh in?

**Comment by ahankinson** [comment]
I already sent Wendy the hex codes, and they're up on the version of Petrucci. Am I missing something?

**Comment by dellsystem** [comment]
I'm not using the version on petrucci to develop anymore. I just noticed that I forgot to add the border, which I'll add in now, but could we just leave the background dark grey? Or does it need to be light blue?

**Comment by dellsystem** [comment]
Addressed in 885ad7c954b2d9e57e8cfb6f61b94c389a44dbce. Github why aren't you linking things

**Comment by dellsystem** [comment]
Are the current colours ok? Can this be closed?

**Comment by ahankinson** [comment]
Yep. Looks great.
