### ISSUE TITLE
How should search work?

### ISSUE THREAD

**Issue by alastair** [DDMAL/salzinnes-original#9]
Currently search is `field:*q*`, so we will match words, and partial words, anywhere in the text. Is this good?

**Comment by dellsystem** [comment]
Sounds fine to me but is there a limit on search results? I seem to be only getting 10 at a time - is that normal?

**Comment by alastair** [comment]
Maybe paging is in play. Let me see

**Comment by alastair** [comment]
I can easily increase the number of results, but it makes the search take quite a bit longer (0.5-1 sec). I can either cap the limit at something like 50 or 100, or we could do a double search - 1 to get 50 results to fill the panel, then another query to get any remaining results.

**Comment by alastair** [comment]
send a &start=10&rows=10 to limit number of results.

If start is empty, it defaults to 0. If rows is empty it defaults to 10. If rows is 'all', it returns (totalresults - start) rows.

**Comment by dellsystem** [comment]
Working on this

**Comment by alastair** [comment]
fyi, server isn't updated yet

**Comment by alastair** [comment]
also some queries aren't working. e.g. blessed virgin, 11,000, etc...

Is this a solr thing? How do we do better indexes?

**Comment by dellsystem** [comment]
I capped it at 50. Does that work?

**Comment by alastair** [comment]
need to search for other criteria too:
Office, Genre, Mode

Cao number ('caoNNNNNN')

Try and fit them all in the one box. We need to be smart about how we choose which one is a good result
